### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by GedeonGrays** [Glease/TC4Tweaks#1]
_Hello o/_

**Thaumcraft 4 Tweaks version:** 1.1.0
**Crash report:** https://pastebin.com/kzPvrkM9

_P.S. Thanks for your time._

**Comment by Glease** [comment]
Your crash report is severely truncated. I need your modlist and forge version to start looking into this problem.

**Comment by Glease** [comment]
I think I know where is come from. This will be fixed in 1.1.2 (waiting curseforge approval)

**Comment by GedeonGrays** [comment]
Thanks, I'll wait.

**Comment by Glease** [comment]
@GedeonGrays Actually, curseforge has approved it already. [check it out](https://www.curseforge.com/minecraft/mc-mods/thaumcraft-4-scrolling/files/3170941)

**Comment by GedeonGrays** [comment]
Yes, I've already seen it. But thanks anyway.
