### ISSUE TITLE
Mandatory added wand text on arcane workbench removal extremely intrusive

### ISSUE THREAD

**Issue by tyrael93** [Glease/TC4Tweaks#10]
## Is your feature request related to a problem? Please describe.
Hello! When disabling the option to use the arcane worktable as a crafting bench, I find the text on every wand crafted by the player to be extremely intrusive, taking up half the screen.

## Describe the solution you'd like
Since this is already an opt-in option, it'd be nice to either remove the message altogether or have a config to disable the wand tooltip.
Thanks in advance for any help on this matter.

## Additional context
With tooltip
![2021-05-19_09 22 08](https://user-images.githubusercontent.com/5557920/118772569-3045b280-b884-11eb-8806-47193fe76db1.png)
Without tooltip
![2021-05-19_09 26 57](https://user-images.githubusercontent.com/5557920/118772756-61be7e00-b884-11eb-87e0-f40b1e2a4d9c.png)

**Comment by Glease** [comment]
An option is added to remove the tooltip.
