### ISSUE TITLE
New search feature in thaumonomicon will sometimes get stuck and not be editable/cancellable

### ISSUE THREAD

**Issue by tyrael93** [Glease/TC4Tweaks#11]
## Mod Version
1.3.0-beta.1

## Describe the bug
I'm loving the new changes with the thaumonomicon expansion and the search tab, thank you so much for adding them. But the search bar seems to be difficult to actually reach to begin with (finding it rather hard to get the thing to click properly for some reason) and it seems to get stuck with no way of going back. I'm on large GUI, tried resizing the page to 1.0 since the bug appeared first with higher multipliers (with 1.5 actually resulting in being unable to click the search tab in any way, even if it was visible) but I can't seem to be able to fix it even with the standard resolution and I can't get rid or edit the search tab on the right.

## To Reproduce
I'm guessing just making the thaumonomicon size multiplier bigger, searching for something and trying to cancel it after switching some tabs.

**FAILURE TO INCLUDE THIS SECTION WILL CAUSE YOUR ISSUE TO BE CLOSED IMMEDIATELY.** 
Your issue will not be considered until you added this section back.

## Expected behavior
Being able to cancel the search/click on search bar after the ordeal

## Screenshots/Screencast
![2021-05-23_10 06 45](https://user-images.githubusercontent.com/5557920/119253074-ba0cbd00-bbaf-11eb-9baf-04ac444635d1.png)
![2021-05-23_10 15 36](https://user-images.githubusercontent.com/5557920/119253102-d872b880-bbaf-11eb-9f2c-4518a5a3cd38.png)

## Additional context
As always, thanks for any input in this matter. 
Cheers!

**Comment by tyrael93** [comment]
I managed to fix this after a few stretches, but I'll keep the issue open just in case it's reproducible.
If it's not, I'll chalk it up to me being a dummy and just not being able to :brain: properly
![2021-05-23_10 25 03](https://user-images.githubusercontent.com/5557920/119253381-4c619080-bbb1-11eb-82e8-1929db1d8a61.png)

**Comment by Glease** [comment]
It's actually a bug that already exist in witching gadgets, where this functionality was taken from. I didn't spent too much time fixing his stuff while integrating it. I'll try to fix it to my best effort.

**Comment by Glease** [comment]
Check out 1.3.0-beta2 on curseforge. It should now close the search result box properly
