### ISSUE TITLE
Search result not clickable

### ISSUE THREAD

**Issue by Skiftcha** [Glease/TC4Tweaks#12]
## Mod Version
1.3.0-beta2

## Describe the bug
Search result appear but not clickable. Any result in red box is not doing anything. But clicking randomly you can find place where click is registered

## To Reproduce
1. set scale to 2.0
2. 
![image](https://user-images.githubusercontent.com/2212585/119321526-69679380-bc85-11eb-869e-4902e350b509.png)
3. 
![image](https://user-images.githubusercontent.com/2212585/119321545-6e2c4780-bc85-11eb-8b10-5dfb5bf1f367.png)
4. 
![image](https://user-images.githubusercontent.com/2212585/119321575-75535580-bc85-11eb-9ca9-00c7f1e76395.png)

**FAILURE TO INCLUDE THIS SECTION WILL CAUSE YOUR ISSUE TO BE CLOSED IMMEDIATELY.** 
Your issue will not be considered until you added this section back.

## Expected behavior
search results can be clicked where it is placed

## Screenshots/Screencast
see ways to reproduce

## Additional context
if important, i have 2560x1080 resolution.

**Comment by Skiftcha** [comment]
btw this tweak is great

**Comment by Glease** [comment]
Fixed in 1.3.0-beta3.

**Comment by Skiftcha** [comment]
yep that works
