### ISSUE TITLE
Left/Right arrow tabs do not move at larger browser size

### ISSUE THREAD

**Issue by truenachtara** [Glease/TC4Tweaks#13]
## Mod Version
1.3.0-beta2

## To Reproduce
1. Have so many addons that you need multiple pages (like in GTNH) and a monitor large enough (I have 1920x1080)
2. Set browserSize to something larger than 1 (I have 1.75)
3. Open the thaumonomnomnomnomicon

## Expected behavior
Left/Right arrow tabs should move out to the sides so they don't cover the middle section.
Recommendation: Could other tabs be moved to the first page if the scale is large enough? It's ugly to have 16 tabs on the left, two on the right, and have to flip to the next page to get five more tabs.

## Screenshots/Screencast
![image](https://user-images.githubusercontent.com/16340367/119750672-6a541d00-be5f-11eb-874d-99598d71a1a2.png)
I use Large gui scale.

**Comment by Glease** [comment]
Remove NotEnoughThaumcraftTabs.
