### ISSUE TITLE
99 basic tabs

### ISSUE THREAD

**Issue by TopPercentageRattata** [Glease/TC4Tweaks#15]
## Mod Version
1.3.0
Using it in GTNH 2.1.0.0, with notenoughthaumcrafttabs removed and also using a newer nei version, but no other changes
## Describe the bug
99 basic tabs clog the thauminomicon

## To Reproduce
Use thauminomicon and see 99 basic tabs that are all empty?

## Expected behavior
Not having 99 random tabs?

## Screenshot
![2021-06-15_00 34 59](https://user-images.githubusercontent.com/16669193/121998623-bebd2f00-cd71-11eb-8ee0-20b9f6036a45.png)

**Comment by TopPercentageRattata** [comment]
![2021-06-15_00 40 01](https://user-images.githubusercontent.com/16669193/121998950-44d97580-cd72-11eb-8511-72bf1be2c1a2.png)
actually its 100 tabs, didnt see 0

**Comment by Glease** [comment]
Fixed in 1.3.1.

**Comment by Glease** [comment]
BTW, I thought I have removed the 1.3.0 jar from curseforge. How on earth did you get it?
