### ISSUE TITLE
Missing tabs in the Thaumonomicon in the GTNH modpack

### ISSUE THREAD

**Issue by Sovereignty89** [Glease/TC4Tweaks#16]
## Mod Version
1.3.2

## Describe the bug
Using your mod found on the GTNH Discord I've noticed the tabs for New Horizons (GTNH) is missing and I believe Witching Gadgets, Blood Magic and Witchery is also missing. All the tabs that require you to go to the next page. All the tabs after Warp Theory seem to be missing. Modpack is GTNH 2.1.0.7a

## To Reproduce
1. Install mod
2. Open Thaumonomicon, awe at the the size
3. Notice missing tabs

**FAILURE TO INCLUDE THIS SECTION WILL CAUSE YOUR ISSUE TO BE CLOSED IMMEDIATELY.** 
Your issue will not be considered until you added this section back.

## Expected behavior
I expected all tabs prior to updating the mod to be there.

## Screenshots/Screencast
![TCMissingTabsGTNH](https://user-images.githubusercontent.com/6663736/122021968-7419d200-cdc6-11eb-8dcd-9b0993fe496d.PNG)

![TCMissingTabsGTNH2](https://user-images.githubusercontent.com/6663736/122022618-0de17f00-cdc7-11eb-808a-ba7435125d5d.PNG)

## Crash Report

N/A

**Comment by Glease** [comment]
it appears I forget to toggle the visibility of navigational buttons.

**Comment by Glease** [comment]
Never mind. Try 1.3.3 to see if it can fix your problem.

**Comment by Sovereignty89** [comment]
Works, thank you!
![TCMissingTabsGTNH3](https://user-images.githubusercontent.com/6663736/122056700-2616c580-cdea-11eb-8a5e-8360a55af914.PNG)
