### ISSUE TITLE
a little "quality of life" fix

### ISSUE THREAD

**Issue by SteamDoge9000** [Glease/TC4Tweaks#18]
## Mod Version
e.g. 1.0.0

Going to go straight to the point, this is a request for a "Quality-of-Life" fix that would make things better

![image](https://user-images.githubusercontent.com/38770780/128067393-bf425e45-3400-4256-b1c2-46d26ed64646.png)

what should be done in my opinion: adjust the new "discorvery" icon to appear on the right side of the tab when its on a tab on the right

**Comment by SteamDoge9000** [comment]
the green dot represents the ajustment

![image](https://user-images.githubusercontent.com/38770780/128067786-eb6c0a26-dc56-495d-a0c6-0c179ac9f178.png)

**Comment by SteamDoge9000** [comment]
on another note, There is this one bug that is anoying and that its hard to select the search box that would be real nice to fix up too, 
![image](https://user-images.githubusercontent.com/38770780/128122269-a8ef95ec-bcf3-4bc0-a9d1-c54948cc3734.png)

**Comment by Glease** [comment]
I have noticed the search box problem before, but so far haven't got the incentive to fix it. Please make a separete issue as a reminder.
