### ISSUE TITLE
Page navigation button rendered over tooltip

### ISSUE THREAD

**Issue by SteamDoge9000** [Glease/TC4Tweaks#19]
## Mod Version
e.g. 1.0.0

![image](https://user-images.githubusercontent.com/38770780/128591363-9fadc28d-903f-4128-8877-69c1c00c34d1.png)

The bug should be self explanatory (The button should not be rendering over the tab)

**Comment by SteamDoge9000** [comment]
hopefully this is an easy fix regarding how rendering is done (I hope)

**Comment by Glease** [comment]
Unfortunately it'd require much more invasive changes into how this whole thing is rendered and would require much more work than a few minutes.

**Comment by SteamDoge9000** [comment]
ah, sorry for the assumption

**Comment by Glease** [comment]
It turns out to be much simpler than I thought. Will have a build soon since I don't have the signing keys with me atm.
