### ISSUE TITLE
Crash on startup [Gregtech 6]

### ISSUE THREAD

**Issue by tyrael93** [Glease/TC4Tweaks#2]
And I'm very sorry to say it's also different from #1, but I think I managed to track the source of the problem.
Here's the pastebin of the crash:
https://pastebin.com/wUvk9khY

Edit: Seems that
>gregtech.asm.transformers.Thaumcraft_AspectLagFix.transform(Thaumcraft_AspectLagFix.java:58)

Is the cultprit. This also happened when using Thaumic fixer and GT6 together https://forum.mechaenetia.com/t/gregtech-asm-transformers-thaumcraft-aspectlagfix/1595, which was a third party mod that fixed the aspect lag but created issues in the game, so greg wrote his own ASM to fix it internally in GT6. As it is the game seems to crash when something interacts with that function. I could bring this up to the GT dev, but even if it could work having both methods coexist would just be redundant. Could you maybe add a config to disable it (or run a check to see if you're running Gregtech 6 and in that case shut off that part of the code) for the sake of compatibility? 

Thank you in advance for any help in fixing this!

**Comment by Glease** [comment]
I'll turn off the ASM if greg's coremod is detected.

**Comment by Glease** [comment]
Release 1.1.1 (currently waiting for approval by curseforge) will automatically turn off the comflicting part if GT6 is detected.

**Comment by tyrael93** [comment]
Nope, that's still happening, just with a different ASM but there's a problem that still seems to be crashing the game .
>Caused by: java.lang.ClassNotFoundException: thaumcraft.common.lib.research.ScanManager
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
	... 45 more
>Caused by: java.lang.ClassCastException: org.objectweb.asm.tree.TypeInsnNode incompatible with org.objectweb.asm.tree.LabelNode
	at gregtech.asm.transformers.Thaumcraft_AspectLagFix.transform(Thaumcraft_AspectLagFix.java:58)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 48 more

Seems to be a greg problem still.
https://pastebin.com/Y5ix5Ei4

**Comment by Glease** [comment]
Seems like GT6 does not like me touching the class at all, even if it's just striping debug info. Will be fixed in 1.1.3 (currently waiting for approval by curseforge)

**Comment by Glease** [comment]
Sorry for being a bit late. Somehow I missed the notificiation email.

**Comment by Glease** [comment]
I've been poking around for a while in game with GT6 installed, it seems to be working just fine now

**Comment by tyrael93** [comment]
no worries, and yeah, greg do :b: like that sometimes
Thanks for going out of your way to add this compat! :rocket:
