### ISSUE TITLE
Client crash rendering item BlockStoneDeviceItem

### ISSUE THREAD

**Issue by doofus9341** [Glease/TC4Tweaks#20]
## Mod Version
1.4.4

## Describe the bug
NPE rendering item thaumcraft.common.blocks.BlockStoneDeviceItem

Details:
Item Type: thaumcraft.common.blocks.BlockStoneDeviceItem@5b0480a3
Item Aux: 9
Item NBT: null
Item Foil: false

## To Reproduce
1. Open Thaumcraft creative menu tab.
2. Scroll to the row containing node stabilizers.

**FAILURE TO INCLUDE THIS SECTION WILL CAUSE YOUR ISSUE TO BE CLOSED IMMEDIATELY.** 
Your issue will not be considered until you added this section back.

## Crash Report
https://paste.ee/p/tR3Yv

**Comment by Glease** [comment]
I can't seem to reproduce the problem in dev. Will try again later in a proper client.

**Comment by Glease** [comment]
Can confirm the bug's existence. Will investigate further later when I'm free.

**Comment by Glease** [comment]
Turns out to be a lot simpler (also a lot more annoying) than I thought. A few lines of code get lost by accident during development. Adding them back solves the problem. Version 1.4.5 should fix this problem.
