### ISSUE TITLE
TC4 Dupes

### ISSUE THREAD

**Issue by DrParadox7** [Glease/TC4Tweaks#22]
## Mod Version
1.4.9

## Describe the bug
**Dupe 1:** TC4 Golems can dupe items using a dispenser and hopper.
**Dupe 2:** Arcane workbench can dupe crafting results using an armor stand (or similar) and a portable hole.

## To Reproduce
**Dupe 1:** https://streamable.com/hp9gh9
**Dupe 2:** https://streamable.com/n10e0c

## Expected behavior
Items inserted into the dispenser to be equal to the items collected by the hoppers and Golems.
Arcane workbench to not drop the recipe result & the ingredients for it.

## Additional context
Thaumcraft-1.7.10-4.2.3.5.jar
Thaumcraft4Tweaks-1.4.9.jar

**Comment by DrParadox7** [comment]
If this can be fixed make sure to send this report to the shadow realm for none to see

**Comment by Glease** [comment]
The portable hole is probably not going to be trivial to fix. For now I'll just add a blacklist on what to not go through.

**Comment by Glease** [comment]
Actually, there is a blacklist in TC4 already. Just add it in configuration would fix this.
