### ISSUE TITLE
Crash on Load: java.lang.NoSuchFieldError: objectTags

### ISSUE THREAD

**Issue by SuperDragonite2172** [Glease/TC4Tweaks#25]
## Mod Version
1.4.14

## Describe the bug
When loading a fairly large modpack with TC4Tweaks, it crashes with `java.lang.NoSuchFieldError: objectTags`.  Unsure if it's because of another mod I have in the pack.

## To Reproduce
1. Load a modpack with TC4Tweaks included.
2. Wait for the crash.

## Expected behavior
I expected the modpack to load as expected without issues.

## Crash Report

https://pastebin.com/MtT6ycBa

## Additional context

1: I'm using custom modpack with a large number of mods.
2: I have 13 TC4 addons other than TC4Tweaks installed:
    i. Forbidden Magic
    ii. Gadomancy
    iii. Magic Bees
    iv. Tainted Magic
    v. Thaumaturgical Knowledge
    vi. Thuamcraft NEI Plugin
    vii. Thaumcraft Node Tracker
    viii. Thaumcraft Reserach Helper
    ix. Thaumic Dyes
    x. Thaumic Fixer
    xi. Thaumic Tinkerer
    xii. ThaumPatch
    xiii. Witching Gadgets

**Comment by Glease** [comment]
This mod does not work with Thaumic Fixer. Part of that mod is already in this mod though, you could just try  without thaumic fixer and see if scanning would cause lags.

**Comment by SuperDragonite2172** [comment]
That fixed the problem.  Thank you very much.
