### ISSUE TITLE
Exception occurred while transforming class net.glease.tc4tweak.modules.objectTag.GetObjectTags:net.glease.tc4tweak.modules.objectTag.GetObjectTags

### ISSUE THREAD

**Issue by syndicate25** [Glease/TC4Tweaks#26]
This does not cause a crash, so is probably not imperative to fix, but I wanted to bring it to your attention.  This is during loading.  I haven't tested this mod to see if anything is affected by this.  Simply wanted to make you aware of the error in the log file that I found.

https://pastebin.com/c19uCkWa

**Comment by syndicate25** [comment]
Actually upon actually using my eyeballs, it looks like this is from Cuchaz Ships.  You can take a look anyway if you want and if that's what you also find, just go ahead and close it out.  No response necessary.

**Comment by Glease** [comment]
It's clearly an issue with cuchaz.ships.core.CoreModTransformer. Nothing I can do here.
