### ISSUE TITLE
Jar collisions don't respect hitbox

### ISSUE THREAD

**Issue by Jerome226** [Glease/TC4Tweaks#29]
## Mod Version
Thaumcraft4Tweaks-1.4.26

## Describe the bug
While jar have a hitbox that respect their model and  the hitbox seem to be respected when hitting the jar block, the player seem to not be able to pass in place where the hitbox doesn't reach. In big words, the player act as like if the jar was a full block, making it annoying and inconsistent.

## To Reproduce
1. Join a multiplayer server with Thaumcraft 4.2.3.5 and Thaumcraft4Tweaks-1.4.23
2. Try to walk inside a jar where the player should be able to
3. See that you can't pass

## Expected behavior
Jar collision to be the same as the jar hitbox

## Screenshots/Screencast
If applicable, add screenshots or short videos to help explain your problem.

https://user-images.githubusercontent.com/55724525/208563517-ecb7390f-7f8f-4b5c-acb5-69b0b53cff55.mp4

## Additional context
Since the jar are affected by this bug, modded jars from addons should probably need to get  the fix too.

**Comment by Glease** [comment]
This seems to be done intentionally... will probably need more investigation.
