### ISSUE TITLE
Emptying buckets in crucibles don't follow vanilla behavior

### ISSUE THREAD

**Issue by Jerome226** [Glease/TC4Tweaks#30]
## Mod Version
Thaumcraft4Tweaks-1.4.26

## Describe the bug
When emptying a water bucket in a crucible, the water bucket will automatically stack in the best slot possible like if you took it on the ground. This make it inconsistent with the vanilla behavior.

## To Reproduce
1. Get a water bucket
2. Click on a empty crucible
3. Notice the empty bucket doesn't end up in the same slot where it should be
4. See inconsistency with vanilla behavior

## Expected behavior
Emptying buckets to work like they do in vanilla

## Screenshots/Screencast
https://user-images.githubusercontent.com/55724525/209749529-b9194c25-b5c9-424e-a783-9e2e0b78775a.mp4

**Comment by Glease** [comment]
I'm not sure what to do with this. Codewise it won't be difficult, however it will probably cause weird sync issues if client side and server side don't all use the updated tc4tweaks. Given the release model of TC4Tweaks this will be considered when the need for a next major release comes up, which is probably the visrelay fix (that has been under development for more than a year on and off somehow)

**Comment by Glease** [comment]
After an actual peek into TC4 code, it appears this whole process doesn't happen on client side whatsoever. Sorry for the delay, should have implemented this months ago 😅 .

**Comment by Glease** [comment]
Implemented by 7cefab6d0d2663d35d23358dfe782caa8bd42f79
