### ISSUE TITLE
Crash on aspect combining

### ISSUE THREAD

**Issue by hron84** [Glease/TC4Tweaks#34]
## Mod Version
e.g. 1.5.5

## Describe the bug
On a fresh world I tried to combine terra and aqua to get victus

## To Reproduce
1. Get the pack Polychromatic World
2. Update Tc4Tweaks and disable NotEnoughThaumcraftTabs
3. Craft a Research Table in a fresh world
4. See a crash

**FAILURE TO INCLUDE THIS SECTION WILL CAUSE YOUR ISSUE TO BE CLOSED IMMEDIATELY.** 
Your issue will not be considered until you added this section back.

## Expected behavior
A Victus aspect forming...

## Screenshots/Screencast
N/A

## Crash Report

[Crashreport](https://pastebin.com/4nQ002BA)

**Comment by Glease** [comment]
Fixed in 1.5.6.
