### ISSUE TITLE
Server crash with latest version 1.5.11

### ISSUE THREAD

**Issue by GraysonUnitt** [Glease/TC4Tweaks#38]
## Mod Version
1.5.11
## Describe the bug
Starting a server with the latest version 1.5.11 causing the server to crash something about StringOrderEntry.
I was able to roll back to version 1.5.10 and not have the crash as this is one of the new features added in 1.5.11.
## To Reproduce
1. Install the required Thaumcraft mods and the addon TC4Tweaks Verson 1.5.11
2. Attempt the launch the server.
3. Server will crash.
## Expected behavior
Server to launch and not crash.
## Crash Report
[crash-2023-07-02_12.23.54-server.txt](https://github.com/Glease/TC4Tweaks/files/11930077/crash-2023-07-02_12.23.54-server.txt)
## Additional context

**Comment by Glease** [comment]
Thanks for finding this out. Should be fixed by [1.5.12 release](https://legacy.curseforge.com/minecraft/mc-mods/tc4tweaks/files/4623210)

**Comment by GraysonUnitt** [comment]
No problem; my pleasure! Thank you for updating this mod to make TC4 better still by far my fav mod and I continue playing in 1.7.10 due to all the great magic mods that stay here. Ill continue to report bugs if I find any I play on a self hosted server so I can weed these out slowly ^^
