### ISSUE TITLE
Jar hitbox broke in MP

### ISSUE THREAD

**Issue by DrParadox7** [Glease/TC4Tweaks#39]
## Mod Version
1.5.12

## Describe the bug
Hitbox from jar spasm player up in Multiplayer only even when `B:smallerJars` is set to false.

## To Reproduce
1) Load up TC4 + dependencies with TC4 Tweaks.
2) Make a server with the same mods.
3) Jump on a jar.
![Tremors](https://github.com/Glease/TC4Tweaks/assets/47131096/17ae7d93-49ec-4402-97a4-3a01dfc38eb2)

## Expected behavior
A standard working hitbox in MP

**Comment by Glease** [comment]
Huh guess this also needs to be synced to client, and if it wasn't, force it to be disabled.

**Comment by Glease** [comment]
It turns out the config is indeed synced to client, but the sync mechanism is very broken. Should be fixed by next release.
