### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by selriam** [Glease/TC4Tweaks#4]
crash: Description: Unexpected error

## Crash Report

 https://pastebin.com/3jEG6B0W

**Comment by Glease** [comment]
Your crash report is truncated and missing following info: 
- signature of my mod
- version of my mod
- mod list

Also please fill the issue template in its entirety. I need these info:
- step to reproduce

**Comment by selriam** [comment]
hi i'm sorry he didn't take the whole crash log over i did it again and now everything had to be in the mod version i can only say that the error comes with all versions i also tested the 1.1.4 even the version had the error also the new beta versions also have this problem and it always occurs when i click and right click with the mouse in my inventory on an object 

https://pastebin.com/PMcKVUiD

**Comment by Glease** [comment]
This is a problem with Thaumic Upholstery mod. It's packaging an outdated thaumcraft API along its jar. Open `Thaumic_Upholstery-1.2_1.7.10.jar` with your favourite ZIP editor (WinRAR, 7zip, whatever) and delete the `thaumcraft` folder in it. You will be good to go with that jar modified. It will not affect how your game behaves unless this mod is broken beyond repair.

Please let me know if this solves your problem.

**Comment by selriam** [comment]
I took the mod out completely and still have the same problem

**Comment by selriam** [comment]
https://pastebin.com/Cg4LcmkV

**Comment by Glease** [comment]
I can't really make sense of this crash. Something is not right here. Anyway, I'll add a fallback for you. Try 1.2.0-beta11 and see if it works for you. Feel free to reopen the issue if it does not.
