### ISSUE TITLE
[Suggestion] Right click to go back, ctrl+scroll to change tabs

### ISSUE THREAD

**Issue by Midnight145** [Glease/TC4Tweaks#41]
## Is your feature request related to a problem? Please describe.

It'd be nice if you could right-click to function like the "return" button at the bottom of research entries (if you click on a research entry from a recipe or something like that) or return to the main GUI if you're at the first-level research entry.

Secondly, it'd be nice if you could hold down ctrl and scroll to cycle between tabs in the thaumonomicon

## Describe the solution you'd like

Unsure if I explained that well at all, here's an example:
In the Thaumic Tinkerer module, you click on Ichorium Tools, to which you click on Silverwood Rod in the recipe to see the research. Right-clicking once from there would take you back to the page you were on Ichorium Tools, and right-clicking again would return you back to the main menu.

## Additional context
HardcoreQuesting does the right-click thing I'm talking about if an example would help.

**Comment by Glease** [comment]
right click is a rather unintuitive way of quiting. no other mod that I know of will bind features like that to right click. NEI and BQ uses backspace, so we might go with the same keybind.

ctrl+scroll to change tab is a bit too "power user". we will need a way to tell user about this features.

**Comment by Midnight145** [comment]
Ahh, alright. I play a _lot_ of Blightfall, which uses HardcoreQuesting heavily, so I'm used to the right-click to go back system. I didn't know it was rarely used.

And yeah, that's fair enough, ctrl+scroll would definitely be rarely used.

**Comment by Midnight145** [comment]
I implemented this functionality myself in [Salis Arcana](https://github.com/rndmorris/Salis-Arcana), which is (or should be, unless something recent broke) compatible with TC4Tweaks
