### ISSUE TITLE
(Need Testing/code reviewing) Crash on modpack when thaumcraft 4 tweaks and Extra utilities is installed

### ISSUE THREAD

**Issue by quentin452** [Glease/TC4Tweaks#42]
## Mod Version
V1.5.15

## Describe the bug
Crash on startup with extra utilities (On Modpack)

## To Reproduce
Steps to the behavior:
1. launch the modpack Biggess Pack Cat Edition
2. Wait 6/7 of loading 
3. get crash

**FAILURE TO INCLUDE THIS SECTION WILL CAUSE YOUR ISSUE TO BE CLOSED IMMEDIATELY.** 
Your issue will not be considered until you added this section back.

## Expected behavior
don't crash

## Crash Report

[crash-2023-10-14_21.01.46-client.txt](https://github.com/Glease/TC4Tweaks/files/12907875/crash-2023-10-14_21.01.46-client.txt)

## Additional context

I'm using Biggess Pack Cat Edition V0.85.9.0(DEV VERSION) modpack
I have alot of TC4 addons installed
Here you can download the dev pack : https://mega.nz/file/TwESAZiB#xz8pj_SNwzVzHImNmZqp_xBCc0QwmDoI758x-Gf4EoY
The crash didn't appear with only thaumcraft/thaumcraft 4 tweaks/extra utilities installed

**Comment by Glease** [comment]
try 1.15.16-alpha.1

**Comment by quentin452** [comment]
where is it?

**Comment by Glease** [comment]
oh that version wasn't actually released on curseforge. let me bump it into a proper release revision

**Comment by quentin452** [comment]
> oh that version wasn't actually released on curseforge. let me bump it into a proper release revision

ok

**Comment by quentin452** [comment]
I am testing the 1.5.16 right now

**Comment by quentin452** [comment]
Fixed by updating thaumcraft 4 tweaks to 1.5.16 thx
