### ISSUE TITLE
Crash on opening Thaumonomicon

### ISSUE THREAD

**Issue by ChromaPIE** [Glease/TC4Tweaks#43]
## Mod Version
1.5.16

## Describe the bug
Title

## To Reproduce
1. Right click when holding a Thaumonomicon
2. Game crashes

**FAILURE TO INCLUDE THIS SECTION WILL CAUSE YOUR ISSUE TO BE CLOSED IMMEDIATELY.** 
Your issue will not be considered until you added this section back.

## Crash Report

https://api.mclo.gs/raw/4EyowCX

## Additional context
on GT:NH

**Comment by Glease** [comment]
cant open your crash report

**Comment by Glease** [comment]
fixed with 1.5.17

**Comment by ChromaPIE** [comment]
oml sorry i sent the wrong link and thanks for the lightning fast fix!
