### ISSUE TITLE
 Thaumonomicon Search Bar is not clickable when Fullscreen is enabled

### ISSUE THREAD

**Issue by Rozmir-Rohi** [Glease/TC4Tweaks#44]
## Mod Version
1.5.17

## Describe the bug
The thaumonomicon search bar becomes unclickable as soon as Minecraft is set to fullscreen (Optifine was not used). The search bar always works when Minecraft is in window mode though.

## To Reproduce
Enter a world with Minecraft in fullscreen mode.

Mods I Used:
 - Thaumcraft-1.7.10-4.2.3.5
 - Baubles-1.7.10-1.0.1.10
 - Thaumcraft4Tweaks-1.5.17
 - netherlicious-3.2.8

## Expected Behavior
If fullscreen mode is enabled, the thaumonomicon search bar will not be clickable.

**Comment by Glease** [comment]
Fixed in 1.5.18-beta.1. I'll close this once this release have received some community testing and promote it to 1.5.18
