### ISSUE TITLE
Suggestion: Research tab percentages like in 1.8.9+

### ISSUE THREAD

**Issue by SonnyLonglegs** [Glease/TC4Tweaks#45]
## Is your feature request related to a problem? Please describe.
I can't tell how close I am to completing a tab, like in future versions of Thaumcraft.

## Describe the solution you'd like
Research percentages on the tab tooltips

## Describe alternatives you've considered
I don't think there really is one besides memorizing it or something.

## Additional context
The only actual use case I can think of is Kami research, besides that it's just a nice completionist thing.

**Comment by Glease** [comment]
implemented in 1.5.18-beta.1.

however, please do test if there is some wonkiness with it, e.g. you have 5 learnt research, but completion counter says you have learnt 7. TC4 research system have many attributes and a lot of them can lead to hidden research. I'm not sure I've enumerated all of them in the build.

**Comment by SonnyLonglegs** [comment]
That was really fast, thank you! And I'll be off to test that now.

**Comment by SonnyLonglegs** [comment]
Update: I don't think it's supposed to do that (shifty characters instead of numbers) unless that's just the research count loading up.
![2023-11-06_11 58 09](https://github.com/Glease/TC4Tweaks/assets/23586053/318ae74d-c608-4c76-bf3c-17d2d30d26bd)

**Comment by Glease** [comment]
@SonnyLonglegs that was intentional. the default config option obfuscate the total count of research on a tab, until you learnt all of them. you can switch it to show total count at all time though.

**Comment by SonnyLonglegs** [comment]
Ohhh, ok, I'll go find the config and try again then.

**Comment by Glease** [comment]
@SonnyLonglegs obfuscation is now removed in beta.2. It now instead adds a `..?` mark to the end of line if you haven't unlocked all research yet.
