### ISSUE TITLE
[Suggestion] Nerf Mighty champions

### ISSUE THREAD

**Issue by anoomolu** [Glease/TC4Tweaks#46]
## Is your feature request related to a problem? Please describe.
The "Mighty" champion mob modifier increases their damage by 4.5x according to ftbwiki. In my experience, they just do a boatload of damage, especially if coming from a Zombie Pigman or other melee mob. In comparison to the other modifiers, it feels extremely overpowered.

## Describe the solution you'd like
I'd like the multiplier to be reduced to 2x, so there is some degree of counterplay in the earlygame/not being forced to bow them down from afar. Alternatively, a config option to adjust the multiplier (with the default being 4.5x like normal) could be nice.

## Describe alternatives you've considered
The config option to disable champion spawns doesn't completely remove them, just limits them to Outer Lands mobs (which still hit like a truck) as far as I'm aware.

**Comment by Glease** [comment]
We don't remove stuff. A config option is however possible.

**Comment by Glease** [comment]
Are you sure it's 4.5x? because from the code it looks like 4x instead. Of course I could misread this code so it's best to test a bit.

**Comment by Glease** [comment]
implemented in [1.5.19](https://legacy.curseforge.com/minecraft/mc-mods/tc4tweaks/files/5023629)
