### ISSUE TITLE
Crash with Witching Gadgets?

### ISSUE THREAD

**Issue by Shahelion** [Glease/TC4Tweaks#47]
## Mod Version
1.5.20

## Describe the bug
Game crashes during startup

**FAILURE TO INCLUDE THIS SECTION WILL CAUSE YOUR ISSUE TO BE CLOSED IMMEDIATELY.** 
Your issue will not be considered until you added this section back.

## Crash Report

https://gist.github.com/Shahelion/9eeade0902384565c2c07cd423fd152f

## Additional context
It was working until I updated this mod. Was previously using version 1.4.7. Witching Gadgets version is 1.2.9.

**Comment by Glease** [comment]
I cannot reproduce the crash with just tc4, widtching gadgets and this mod. Soeither you are using a custom build of witching gadgets or another mod is causing incompatiblity. It's hard to tell what exactly is breaking with the given information. 

1. There are like 40 versions between 1.4.7 and 1.5.20. I don't know which change makes it break
2. There are a lot other mods in your pack that it's takes an unreasonable amount of time just for me to recreate your test environment.
3. The crash report points to a line that is impossible to error.

so my suggestion:
1. try bisect a version of tc4tweaks that would start to break
2. try bisect the faulty mod

**Comment by Shahelion** [comment]
https://github.com/KryptonCaptain/WitchingGadgets/releases/tag/1.2.9

This is the version of Witching Gadgets, forgot it was a fork.

Will try to narrow down the version that causes the problem and update here.

**Comment by Glease** [comment]
That version is sort of well known and I was testing against that build as well. What I meant is a deeply customized WitchingGadgets like GTNH's version does. Though it looks like that is not the case.

**Comment by Shahelion** [comment]
I have tested every version from 1.4.8 onwards, they all gave the same crash.

**Comment by Glease** [comment]
1.4.8 added a few optimization patches. Which shouldn't cause the crash as shown in your log. I can only assume it's some other mod interefering. 

You can stick to 1.4.7 for now. If you have the extra time, you can try bisect which mod is interefering.
