### ISSUE TITLE
Request: Config to remove loot bags from champions

### ISSUE THREAD

**Issue by brandyyn** [Glease/TC4Tweaks#48]
Hey, I love champion mobs in thaumcraft, challenges are good! but I don't like the loot bags and in mob farms you get soooo many. Could there please be a config option to stop champions from dropping loot bags? unless there's another solution? :0

**Comment by Glease** [comment]
while this is not immediately out of the scope, there are plenty of existing mods that can do the same. CraftTweaker or [edit mob drop](https://www.curseforge.com/minecraft/mc-mods/edit-mob-drops) should both do the trick.

leaving this open for now, in case I got time later.

**Comment by brandyyn** [comment]
thaumic mixins added this feature for me
