### ISSUE TITLE
Request: Thaumonomicon table

### ISSUE THREAD

**Issue by brandyyn** [Glease/TC4Tweaks#49]
I think it would be super cool to have a thaumonomicon table, like a table you can access your thaumonomicon from instead of always having to hold it, you can just open your book by right clicking the block, unless something like this already exists? Just to be clear, not a block where you can take the book out of then use, but a block that you can just right click and it opens the GUI

**Comment by Glease** [comment]
unfortunately this is out of the scope of this mod

**Comment by fluid-decanter** [comment]
While understandably out of scope for this mod, I would like to inform OP that there is a block like this in the Thaumcraft addon mod Gadomancy, called "Book of Knowledge". I think there are similar blocks in other addon mods, but none come to mind.
