### ISSUE TITLE
Minecraft Crash Report

### ISSUE THREAD

**Issue by selriam** [Glease/TC4Tweaks#5]
now another crash 

https://pastebin.com/fZw8H1nJ

**Comment by Glease** [comment]
Now this is getting weird. Basically, it *should* be the same problem of certain addon bundling an outdated thaumcraft API, though I'm not sure which. Could you please somehow send me your mods? You can find me via [this discord server](https://discord.gg/EdVX8Srm2c), or you can send it via some online file sharing service, e.g. onedrive, dropbox, as long as it doesn't want me to click through a thousand ads to get your file.
