### ISSUE TITLE
World reload crash (TCTweaks Beta-12)

### ISSUE THREAD

**Issue by tyrael93** [Glease/TC4Tweaks#8]
## Mod Version
TCTweaks-Beta-12

## Describe the bug
An incompatibility with Minetweaker when reloading the world causes the game to crash and renders the save inaccessible until the instance is killed and restarted.

## To Reproduce
Reload a world with minetweaker enabled.

**FAILURE TO INCLUDE THIS SECTION WILL CAUSE YOUR ISSUE TO BE CLOSED IMMEDIATELY.** 
Your issue will not be considered until you added this section back. {**ok**}

## Expected behavior
Not crashing on world reload, as it didn't happen in Beta-11.

## Crash Report
Technically not a crash report since minecraft does not crash, only the save, but it's the same in any case, here: https://pastebin.com/Ut1M5eMH

## Additional context
Modtweaker and MTutils may also be required to reproduce the crash, even if the crashlog says modtweaker3 errored at worldload.

As always, thanks in advance.

**Comment by Glease** [comment]
An apparent oversight. Will be fixed in next beta.
