### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by GedeonGrays** [Glease/TC4Tweaks#9]
## Mod Version
1.2.0-rc1

## Describe the bug
Client crash on startup.

**FAILURE TO INCLUDE THIS SECTION WILL CAUSE YOUR ISSUE TO BE CLOSED IMMEDIATELY.** 
Your issue will not be considered until you added this section back.

## Expected behavior
I expect the client to start without crashing.

## Crash Report

https://pastebin.com/Ya0A3fL6

## Additional context
Several previous versions of the mod also caused a crash.

**Comment by Glease** [comment]
Stupid code error. Weird as why it didn't crash on my end in the first place. Please try 1.2.0-rc2 and see if it fix this error.

**Comment by GedeonGrays** [comment]
Unfortunately, the crash remained, but changed a bit: https://pastebin.com/s7frqM5D

**Comment by Glease** [comment]
It's a separate problem that I thought I have fixed weeks ago. Apparently I didn't. 😢

**Comment by GedeonGrays** [comment]
If you know how to fix this error, then this is the main thing ;)
I will wait as long as necessary. Yet, apparently, I am the only one so far who encountered this error or reported it. So the priority of the work is still yours.

**Comment by Glease** [comment]
Try 1.2.0-rc3. It's a bug and it's there. It won't go away even if it only affect one player. It's not really hard to fix, or something I cannot understand what's happening anyway.

**Comment by GedeonGrays** [comment]
Yep, as far as I can tell, the issue has been resolved. The client started without problems. Thank you for your prompt work.
